version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: npx hardhat test
      - store_artifacts:
          path: target
