version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3
commands:
  fetch:
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
  build:
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: "16.14.2"
      - run: node --version
  test:
    steps:
      - run: npm i
      - run: npx hardhat clean
      - run: npx hardhat coverage
      - codecov/upload
executors:
  docker-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  Hello-World:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  fetch-code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - fetch
  install-node-and-test:
    executor: docker-executor
    steps:
      - build
      - test
workflows:
  test-app:
    jobs:
      - fetch-code
      - install-node-and-test:
          requires:
            - fetch-code
