version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
commands:
  fetch:
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
  test:
    steps:
      - run: npm i && npx hardhat coverage
executors:
  docker-executor:
    docker:
      - image: "cimg/base:stable"
jobs:
  Hello-World:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  fetch-code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - fetch
  install-node-and-test:
    executor: docker-executor
    steps:
      - test
workflows:
  test-app:
    jobs:
      - Hello-World
      - fetch-code:
          requires:
            - Hello-World
      - install-node-and-test:
          requires:
            - fetch-code
          post-steps:
            - codecov/upload
